### ISSUE TITLE
Not really an issue but

### ISSUE THREAD

**Issue by vinerich** [universal-geocoder/universal-geocoder-js#14]
how can I buy you a coffee?

I came here from [node-geocoder](https://github.com/nchaulet/node-geocoder) which brought me to [geocoder-js](https://github.com/geocoder-php/geocoder-js) which brought me here through your PR.

You saved me probably a lot of time and/or server pressure by not having to rely on either a self made browser solution or a server-side implementation.

Just want to say a big thanks for this project!! Sadly it is not that visible.

I suppose this can be considered closed 😄 

**Edit:** Works great btw 🔥 

**Second edit:** Maybe for a few unprofessional users a description where to get the default browser user-agent would be nice. You could just drop `navigator.userAgent`. Not necessary but also not much effort to change it.
My fingers are faster than my brain .. OSM Provider is meant in the second edit.

**Comment by alanpoulain** [comment]
Thank you for your kind comment (I didn't see it before today)!

I know it's not very visible and used yet but I plan to write a least one article once the 1.0 is out and hopefully it will be more known afterwards.

For the User-Agent of OSM, it needs to be not the browser one, but a custom user-defined one (for instance: "My Awesome Library 1.0"). See also https://operations.osmfoundation.org/policies/nominatim/.
